In [ ]:
import numpy as np
import pandas as pd
 
features_field_full = pd.read_pickle('/content/drive/My Drive/Copy of features_field.pkl', compression = 'gzip')
features_field_full = features_field_full.dropna()
features_field_full.reset_index(drop=True,inplace=True)
features_field = features_field_full.drop(columns = ['user_id','activity_type_id','start','finish','length'])
features_field.reset_index(drop=True, inplace=True)
# features_field.columns = ['']
features_field.shape

(24583, 223)

In [ ]:
from sklearn.model_selection import train_test_split

data = features_field.to_numpy()
X_train, X_test, y_train, y_test = train_test_split(data, ((features_field_full['activity_type_id']-1).to_numpy()), test_size=0.33, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(16470, 223)
(8113, 223)
(16470,)
(8113,)


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score
model = SVC(kernel = 'rbf' , C = 1000 , gamma = 0.0001)
model.fit(X_train , y_train)
y_pred = model.predict(X_test)

In [ ]:
print("Confusion Matrix: \n\n",confusion_matrix(y_test,y_pred))
print("\n\nReport: \n\n",classification_report(y_test,y_pred))
print("Accuracy: ",accuracy_score(y_test,y_pred))

Confusion Matrix: 

 [[   0    0    0    0   58    0    0    0    0    0]
 [   0    0    0    0    4    0    0    0    0    0]
 [   0    0    4    0  372    0    0    0    0    0]
 [   0    0    0  792 1194    0    0    0    0    0]
 [   0    0    0    3 4943    0    0    0    0    0]
 [   0    0    0    0    2    0    0    0    0    0]
 [   0    0    0    1  359    0  168    0    0    0]
 [   0    0    0    0   14    0    0    0    0    0]
 [   0    0    0    0    6    0    0    0    0    0]
 [   0    0    0    1  118    0    0    0    0   74]]


Report: 

               precision    recall  f1-score   support

           0       0.00      0.00      0.00        58
           1       0.00      0.00      0.00         4
           2       1.00      0.01      0.02       376
           3       0.99      0.40      0.57      1986
           4       0.70      1.00      0.82      4946
           5       0.00      0.00      0.00         2
           6       1.00      0.32      0.48       528
  

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
